# Generated by Django 5.1.2 on 2025-01-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catrgory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
