# Generated by Django 5.1.2 on 2025-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kada', models.CharField(max_length=100)),
                ('heart', models.CharField(max_length=100)),
                ('boobs', models.IntegerField()),
                ('dakka_dawasa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
