# Generated by Django 5.1.2 on 2025-01-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_crush'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crush',
        ),
    ]
